image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk
      export ANDROID_HOME=/opt/android-sdk
      export PATH=$PATH:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools
      sdkmanager --update
  - command: ./gradlew build
